# Generated by Django 4.2.7 on 2023-11-26 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Coords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(max_length=30, verbose_name='Широта')),
                ('longitude', models.FloatField(max_length=30, verbose_name='Долгота')),
                ('height', models.IntegerField(verbose_name='Высота')),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winter', models.CharField(choices=[('1b', '1Б'), ('2a', '2A'), ('2b', '2Б'), ('3a', '3A'), ('3b', '3Б'), ('4a', '4A'), ('4b', '4Б'), ('5b', '5Б'), ('6a', '6A'), ('6b', '6Б')], max_length=2, verbose_name='Зима')),
                ('spring', models.CharField(choices=[('1b', '1Б'), ('2a', '2A'), ('2b', '2Б'), ('3a', '3A'), ('3b', '3Б'), ('4a', '4A'), ('4b', '4Б'), ('5b', '5Б'), ('6a', '6A'), ('6b', '6Б')], max_length=2, verbose_name='Весна')),
                ('summer', models.CharField(choices=[('1b', '1Б'), ('2a', '2A'), ('2b', '2Б'), ('3a', '3A'), ('3b', '3Б'), ('4a', '4A'), ('4b', '4Б'), ('5b', '5Б'), ('6a', '6A'), ('6b', '6Б')], max_length=2, verbose_name='Лето')),
                ('autumn', models.CharField(choices=[('1b', '1Б'), ('2a', '2A'), ('2b', '2Б'), ('3a', '3A'), ('3b', '3Б'), ('4a', '4A'), ('4b', '4Б'), ('5b', '5Б'), ('6a', '6A'), ('6b', '6Б')], max_length=2, verbose_name='Осень')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('fam', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('otc', models.CharField(blank=True, max_length=255, null=True, verbose_name='Отчество')),
                ('phone', models.CharField(max_length=12, verbose_name='Телефон')),
                ('email', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True)),
                ('cat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='routes.category')),
            ],
        ),
    ]
